apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-container
        image: lokesh815/my-first-docker-image1:latest
        volumeMounts:
        - name: app-connection
          mountPath: /opt
        ports:
        - containerPort: 3000
      volumes:
      - name: app-connection
        configMap:
          name: app-config
